package dev.skomlach.biometric.compat

enum class BiometricType {
    BIOMETRIC_FINGERPRINT,
    BIOMETRIC_FACE,
    BIOMETRIC_IRIS,
    BIOMETRIC_VOICE,
    BIOMETRIC_PALMPRINT,
    BIOMETRIC_HEARTRATE,
    BIOMETRIC_BEHAVIOR,
    BIOMETRIC_ANY
}