$voiceKeys = @(
    'biometriccompat_voice_help_timeout',
    'biometriccompat_voice_help_unavailable',
    'biometriccompat_voice_help_permission_required',
    'biometriccompat_voice_help_sample_required',
    'biometriccompat_voice_help_not_registered',
    'biometriccompat_voice_help_enrolled',
    'biometriccompat_voice_help_accepted',
    'biometriccompat_voice_help_not_matched',
    'biometriccompat_voice_help_lockout',
    'biometriccompat_voice_help_lockout_permanent',
    'biometriccompat_voice_help_sample_valid',
    'biometriccompat_voice_help_sample_missing',
    'biometriccompat_voice_help_sample_rate_low',
    'biometriccompat_voice_help_sample_short',
    'biometriccompat_voice_help_sample_long',
    'biometriccompat_voice_help_sample_quiet',
    'biometriccompat_voice_help_sample_flat',
    'biometriccompat_voice_help_sample_clipped',
    'biometriccompat_voice_help_sample_replay_risk',
    'biometriccompat_voice_help_embedding_invalid',
    'biometriccompat_voice_button_content_description',
    'biometriccompat_voice_overlay_title_enroll',
    'biometriccompat_voice_overlay_title_auth',
    'biometriccompat_voice_overlay_hint_enroll',
    'biometriccompat_voice_overlay_hint_auth',
    'biometriccompat_voice_overlay_phrase',
    'biometriccompat_voice_record_start',
    'biometriccompat_voice_record_stop',
    'biometriccompat_voice_record_ready',
    'biometriccompat_voice_progress_enroll',
    'biometriccompat_voice_progress_auth_ready',
    'biometriccompat_voice_progress_auth_missing',
    'biometriccompat_voice_action_enroll',
    'biometriccompat_voice_action_verify',
    'biometriccompat_voice_error_recorder_unavailable',
    'biometriccompat_voice_error_no_speech',
    'biometriccompat_voice_error_sample_too_short',
    'biometriccompat_voice_error_sample_missing',
    'biometriccompat_voice_error_recording_failed',
    'biometriccompat_voice_auto_auth_start',
    'biometriccompat_voice_auto_detected',
    'biometriccompat_voice_auto_enroll_recording_started',
    'biometriccompat_voice_auto_sample_saved',
    'biometriccompat_voice_status_recording',
    'biometriccompat_voice_status_checking'
)

$sharedKeys = @(
    'biometriccompat_software_hardware_backed_crypto_unsupported',
    'biometriccompat_sensor_privacy_start_use_mic_notification_content_title',
    'biometriccompat_sensor_privacy_start_use_dialog_turn_on_button',
    'biometriccompat_biometric_dialog_default_title',
    'biometriccompat_biometric_dialog_default_subtitle'
)

$voiceRows = @'
values-uk~Час очікування автентифікації голосом вичерпано~Автентифікація голосом недоступна~Для автентифікації голосом потрібен дозвіл на мікрофон~Потрібен голосовий зразок. Надайте записаний голосовий зразок або попередньо обчислений голосовий вектор.~Не зареєстровано жодної голосової біометрії. Запишіть і зареєструйте голосові зразки перед автентифікацією.~Голосовий шаблон зареєстровано: %1$s~Голосову біометрію підтверджено~Голосова біометрія не збіглася~Автентифікацію голосом тимчасово заблоковано~Автентифікацію голосом заблоковано назавжди~Голосовий зразок коректний~Голосовий зразок відсутній або неповний. Надайте PCM-аудіо або коректний голосовий вектор.~Частота дискретизації голосового зразка надто низька. За можливості використовуйте моно PCM 16 кГц.~Голосовий зразок надто короткий. Говоріть природно щонайменше одну секунду.~Голосовий зразок надто довгий. Тримайте голосовий зразок коротшим за вісім секунд.~Голосовий зразок надто тихий. Підійдіть ближче до мікрофона й спробуйте ще раз.~У голосовому зразку замало варіації. Скажіть чітку фразу й спробуйте ще раз.~Голосовий зразок перевантажений. Зменште чутливість мікрофона або трохи відсуньтеся.~Голосовий зразок схожий на повторений або синтетичний. Запишіть нову природну фразу.~Голосовий вектор некоректний. Надайте непорожній вектор диктора зі скінченними значеннями.~Захоплення голосу~Запишіть голосовий зразок~Підтвердьте свій голос~Запишіть %1$d природних зразків свого голосу. Говоріть 2-4 секунди щоразу.~Запишіть один природний голосовий зразок. Говоріть 2-4 секунди.~Фраза: %1$s~Почати запис~Зупинити запис~Зразок готовий~Записано зразків: %1$d/%2$d~Голосовий зразок готовий~Голосовий зразок ще не записано~Зареєструвати~Перевірити~Запис голосу недоступний на цьому пристрої.~Мовлення не виявлено. Говоріть чітко й спробуйте ще раз.~Голосовий зразок надто короткий. Говоріть природно щонайменше одну секунду.~Запишіть голосовий зразок, перш ніж продовжити.~Не вдалося записати голос. Спробуйте ще раз.~Слухаємо голос~Голос виявлено~Голосовий зразок %1$d із %2$d: запис розпочато~Голосовий зразок %1$d із %2$d збережено~Запис голосового зразка...~Перевірка голосу
values-ru~Время ожидания аутентификации по голосу истекло~Аутентификация по голосу недоступна~Для аутентификации по голосу требуется разрешение на микрофон~Требуется голосовой образец. Предоставьте записанный голосовой образец или заранее вычисленный голосовой вектор.~Не зарегистрировано ни одной голосовой биометрии. Запишите и зарегистрируйте голосовые образцы перед аутентификацией.~Голосовой шаблон зарегистрирован: %1$s~Голосовая биометрия подтверждена~Голосовая биометрия не совпала~Аутентификация по голосу временно заблокирована~Аутентификация по голосу заблокирована навсегда~Голосовой образец корректен~Голосовой образец отсутствует или неполон. Предоставьте PCM-аудио или корректный голосовой вектор.~Частота дискретизации голосового образца слишком низкая. По возможности используйте моно PCM 16 кГц.~Голосовой образец слишком короткий. Говорите естественно не менее одной секунды.~Голосовой образец слишком длинный. Держите голосовой образец короче восьми секунд.~Голосовой образец слишком тихий. Подойдите ближе к микрофону и попробуйте снова.~В голосовом образце слишком мало вариации. Произнесите четкую фразу и попробуйте снова.~Голосовой образец перегружен. Уменьшите усиление микрофона или немного отодвиньтесь.~Голосовой образец похож на повторенный или синтетический. Запишите новую естественную фразу.~Голосовой вектор некорректен. Предоставьте непустой вектор диктора с конечными значениями.~Захват голоса~Записать голосовой образец~Подтвердите свой голос~Запишите %1$d естественных образцов своего голоса. Говорите по 2-4 секунды каждый раз.~Запишите один естественный голосовой образец. Говорите 2-4 секунды.~Фраза: %1$s~Начать запись~Остановить запись~Образец готов~Записано образцов: %1$d/%2$d~Голосовой образец готов~Голосовой образец еще не записан~Зарегистрировать~Проверить~Запись голоса недоступна на этом устройстве.~Речь не обнаружена. Говорите четко и попробуйте снова.~Голосовой образец слишком короткий. Говорите естественно не менее одной секунды.~Запишите голосовой образец, прежде чем продолжить.~Не удалось записать голос. Попробуйте снова.~Слушаем голос~Голос обнаружен~Голосовой образец %1$d из %2$d: запись начата~Голосовой образец %1$d из %2$d сохранен~Запись голосового образца...~Проверка голоса
values-de~Zeitüberschreitung bei der Sprachauthentifizierung~Sprachauthentifizierung ist nicht verfügbar~Für die Sprachauthentifizierung ist die Mikrofonberechtigung erforderlich~Eine Sprachprobe ist erforderlich. Stellen Sie eine aufgezeichnete Sprachprobe oder ein vorab berechnetes Stimme-Embedding bereit.~Es ist keine Sprachbiometrie registriert. Nehmen Sie vor der Authentifizierung Sprachproben auf und registrieren Sie sie.~Sprachvorlage registriert: %1$s~Sprachbiometrie akzeptiert~Sprachbiometrie stimmte nicht überein~Sprachauthentifizierung ist vorübergehend gesperrt~Sprachauthentifizierung ist dauerhaft gesperrt~Sprachprobe ist gültig~Die Sprachprobe fehlt oder ist unvollständig. Stellen Sie PCM-Audio oder ein gültiges Stimme-Embedding bereit.~Die Abtastrate der Sprachprobe ist zu niedrig. Verwenden Sie nach Möglichkeit 16-kHz-Mono-PCM.~Die Sprachprobe ist zu kurz. Sprechen Sie natürlich mindestens eine Sekunde lang.~Die Sprachprobe ist zu lang. Halten Sie die Sprachprobe unter acht Sekunden.~Die Sprachprobe ist zu leise. Gehen Sie näher an das Mikrofon heran und versuchen Sie es erneut.~Die Sprachprobe hat zu wenig Variation. Sprechen Sie eine klare Phrase und versuchen Sie es erneut.~Die Sprachprobe ist übersteuert. Verringern Sie die Mikrofonverstärkung oder gehen Sie etwas weiter weg.~Die Sprachprobe wirkt wiederholt oder synthetisch. Nehmen Sie eine neue natürliche Phrase auf.~Das Stimme-Embedding ist ungültig. Stellen Sie ein nicht leeres Sprecher-Embedding mit endlichen Werten bereit.~Spracherfassung~Sprachprobe aufnehmen~Bestätigen Sie Ihre Stimme~Nehmen Sie %1$d natürliche Sprachproben Ihrer Stimme auf. Sprechen Sie jedes Mal 2-4 Sekunden.~Nehmen Sie eine natürliche Sprachprobe auf. Sprechen Sie 2-4 Sekunden.~Phrase: %1$s~Aufnahme starten~Aufnahme stoppen~Probe bereit~Aufgenommene Proben: %1$d/%2$d~Sprachprobe bereit~Noch keine Sprachprobe aufgenommen~Registrieren~Prüfen~Sprachrekorder ist auf diesem Gerät nicht verfügbar.~Keine Sprache erkannt. Sprechen Sie deutlich und versuchen Sie es erneut.~Die Sprachprobe ist zu kurz. Sprechen Sie natürlich mindestens eine Sekunde lang.~Nehmen Sie vor dem Fortfahren eine Sprachprobe auf.~Sprachaufnahme fehlgeschlagen. Versuchen Sie es erneut.~Auf Stimme warten~Stimme erkannt~Sprachprobe %1$d von %2$d: Aufnahme gestartet~Sprachprobe %1$d von %2$d gespeichert~Sprachprobe wird aufgenommen...~Stimme wird geprüft
values-es~Se agotó el tiempo de autenticación por voz~La autenticación por voz no está disponible~Se requiere permiso de micrófono para la autenticación por voz~Se requiere una muestra de voz. Proporciona una muestra grabada o una incrustación de voz calculada previamente.~No hay ninguna biometría de voz registrada. Graba y registra muestras de voz antes de autenticarte.~Plantilla de voz registrada: %1$s~Biometría de voz aceptada~La biometría de voz no coincidió~La autenticación por voz está bloqueada temporalmente~La autenticación por voz está bloqueada permanentemente~La muestra de voz es válida~La muestra de voz falta o está incompleta. Proporciona audio PCM o una incrustación de voz válida.~La frecuencia de muestreo de la muestra de voz es demasiado baja. Usa PCM mono de 16 kHz cuando sea posible.~La muestra de voz es demasiado corta. Habla de forma natural durante al menos un segundo.~La muestra de voz es demasiado larga. Mantén la muestra de voz por debajo de ocho segundos.~La muestra de voz es demasiado baja. Acércate al micrófono e inténtalo de nuevo.~La muestra de voz tiene muy poca variación. Di una frase clara e inténtalo de nuevo.~La muestra de voz está saturada. Baja la ganancia del micrófono o aléjate un poco.~La muestra de voz parece repetida o sintética. Graba una frase natural nueva.~La incrustación de voz no es válida. Proporciona una incrustación de hablante no vacía con valores finitos.~Captura de voz~Grabar muestra de voz~Confirma tu voz~Graba %1$d muestras naturales de tu voz. Habla durante 2-4 segundos cada vez.~Graba una muestra de voz natural. Habla durante 2-4 segundos.~Frase: %1$s~Iniciar grabación~Detener grabación~Muestra lista~Muestras grabadas: %1$d/%2$d~Muestra de voz lista~Aún no se ha grabado ninguna muestra de voz~Registrar~Verificar~La grabadora de voz no está disponible en este dispositivo.~No se detectó voz. Habla con claridad e inténtalo de nuevo.~La muestra de voz es demasiado corta. Habla de forma natural durante al menos un segundo.~Graba una muestra de voz antes de continuar.~La grabación de voz falló. Inténtalo de nuevo.~Escuchando la voz~Voz detectada~Muestra de voz %1$d de %2$d: grabación iniciada~Muestra de voz %1$d de %2$d guardada~Grabando muestra de voz...~Comprobando la voz
values-b+es+419~Se agotó el tiempo de autenticación por voz~La autenticación por voz no está disponible~Se requiere permiso de micrófono para la autenticación por voz~Se requiere una muestra de voz. Proporciona una muestra grabada o una incrustación de voz calculada previamente.~No hay ninguna biometría de voz registrada. Graba y registra muestras de voz antes de autenticarte.~Plantilla de voz registrada: %1$s~Biometría de voz aceptada~La biometría de voz no coincidió~La autenticación por voz está bloqueada temporalmente~La autenticación por voz está bloqueada permanentemente~La muestra de voz es válida~La muestra de voz falta o está incompleta. Proporciona audio PCM o una incrustación de voz válida.~La frecuencia de muestreo de la muestra de voz es demasiado baja. Usa PCM mono de 16 kHz cuando sea posible.~La muestra de voz es demasiado corta. Habla de forma natural durante al menos un segundo.~La muestra de voz es demasiado larga. Mantén la muestra de voz por debajo de ocho segundos.~La muestra de voz es demasiado baja. Acércate al micrófono e inténtalo de nuevo.~La muestra de voz tiene muy poca variación. Di una frase clara e inténtalo de nuevo.~La muestra de voz está saturada. Baja la ganancia del micrófono o aléjate un poco.~La muestra de voz parece repetida o sintética. Graba una frase natural nueva.~La incrustación de voz no es válida. Proporciona una incrustación de hablante no vacía con valores finitos.~Captura de voz~Grabar muestra de voz~Confirma tu voz~Graba %1$d muestras naturales de tu voz. Habla durante 2-4 segundos cada vez.~Graba una muestra de voz natural. Habla durante 2-4 segundos.~Frase: %1$s~Iniciar grabación~Detener grabación~Muestra lista~Muestras grabadas: %1$d/%2$d~Muestra de voz lista~Aún no se ha grabado ninguna muestra de voz~Registrar~Verificar~La grabadora de voz no está disponible en este dispositivo.~No se detectó voz. Habla con claridad e inténtalo de nuevo.~La muestra de voz es demasiado corta. Habla de forma natural durante al menos un segundo.~Graba una muestra de voz antes de continuar.~La grabación de voz falló. Inténtalo de nuevo.~Escuchando la voz~Voz detectada~Muestra de voz %1$d de %2$d: grabación iniciada~Muestra de voz %1$d de %2$d guardada~Grabando muestra de voz...~Comprobando la voz
values-fr~Le délai d'authentification vocale est dépassé~L'authentification vocale n'est pas disponible~L'autorisation du microphone est requise pour l'authentification vocale~Un échantillon vocal est requis. Fournissez un échantillon vocal enregistré ou une empreinte vocale précalculée.~Aucune biométrie vocale n'est enregistrée. Enregistrez des échantillons vocaux avant de vous authentifier.~Modèle vocal enregistré : %1$s~Biométrie vocale acceptée~La biométrie vocale ne correspond pas~L'authentification vocale est temporairement verrouillée~L'authentification vocale est verrouillée de façon permanente~L'échantillon vocal est valide~L'échantillon vocal est manquant ou incomplet. Fournissez un audio PCM ou une empreinte vocale valide.~La fréquence d'échantillonnage de l'échantillon vocal est trop basse. Utilisez si possible du PCM mono 16 kHz.~L'échantillon vocal est trop court. Parlez naturellement pendant au moins une seconde.~L'échantillon vocal est trop long. Gardez l'échantillon vocal en dessous de huit secondes.~L'échantillon vocal est trop faible. Rapprochez-vous du microphone et réessayez.~L'échantillon vocal manque de variation. Prononcez une phrase claire et réessayez.~L'échantillon vocal est saturé. Réduisez le gain du microphone ou éloignez-vous légèrement.~L'échantillon vocal semble répété ou synthétique. Enregistrez une nouvelle phrase naturelle.~L'empreinte vocale n'est pas valide. Fournissez une empreinte vocale non vide avec des valeurs finies.~Capture vocale~Enregistrer un échantillon vocal~Confirmez votre voix~Enregistrez %1$d échantillons naturels de votre voix. Parlez pendant 2-4 secondes à chaque fois.~Enregistrez un échantillon vocal naturel. Parlez pendant 2-4 secondes.~Phrase : %1$s~Démarrer l'enregistrement~Arrêter l'enregistrement~Échantillon prêt~Échantillons enregistrés : %1$d/%2$d~Échantillon vocal prêt~Aucun échantillon vocal n'a encore été enregistré~Enregistrer~Vérifier~L'enregistreur vocal n'est pas disponible sur cet appareil.~Aucune voix détectée. Parlez clairement et réessayez.~L'échantillon vocal est trop court. Parlez naturellement pendant au moins une seconde.~Enregistrez un échantillon vocal avant de continuer.~L'enregistrement vocal a échoué. Réessayez.~Écoute de la voix~Voix détectée~Échantillon vocal %1$d sur %2$d : enregistrement démarré~Échantillon vocal %1$d sur %2$d enregistré~Enregistrement de l'échantillon vocal...~Vérification de la voix
values-it~Timeout dell'autenticazione vocale~L'autenticazione vocale non è disponibile~Per l'autenticazione vocale è necessaria l'autorizzazione del microfono~È richiesto un campione vocale. Fornisci un campione vocale registrato o un embedding vocale precalcolato.~Nessuna biometria vocale è registrata. Registra campioni vocali prima di autenticarti.~Modello vocale registrato: %1$s~Biometria vocale accettata~La biometria vocale non corrisponde~L'autenticazione vocale è temporaneamente bloccata~L'autenticazione vocale è bloccata in modo permanente~Il campione vocale è valido~Il campione vocale manca o è incompleto. Fornisci audio PCM o un embedding vocale valido.~La frequenza di campionamento del campione vocale è troppo bassa. Usa PCM mono a 16 kHz quando possibile.~Il campione vocale è troppo corto. Parla in modo naturale per almeno un secondo.~Il campione vocale è troppo lungo. Mantieni il campione vocale sotto gli otto secondi.~Il campione vocale è troppo basso. Avvicinati al microfono e riprova.~Il campione vocale ha troppo poca variazione. Pronuncia una frase chiara e riprova.~Il campione vocale è distorto. Riduci il guadagno del microfono o allontanati leggermente.~Il campione vocale sembra ripetuto o sintetico. Registra una nuova frase naturale.~L'embedding vocale non è valido. Fornisci un embedding del parlante non vuoto con valori finiti.~Acquisizione vocale~Registra campione vocale~Conferma la tua voce~Registra %1$d campioni naturali della tua voce. Parla per 2-4 secondi ogni volta.~Registra un campione vocale naturale. Parla per 2-4 secondi.~Frase: %1$s~Avvia registrazione~Ferma registrazione~Campione pronto~Campioni registrati: %1$d/%2$d~Campione vocale pronto~Nessun campione vocale ancora registrato~Registra~Verifica~Il registratore vocale non è disponibile su questo dispositivo.~Nessun parlato rilevato. Parla chiaramente e riprova.~Il campione vocale è troppo corto. Parla in modo naturale per almeno un secondo.~Registra un campione vocale prima di continuare.~Registrazione vocale non riuscita. Riprova.~In ascolto della voce~Voce rilevata~Campione vocale %1$d di %2$d: registrazione avviata~Campione vocale %1$d di %2$d salvato~Registrazione del campione vocale...~Controllo della voce
values-nl~Time-out bij spraakauthenticatie~Spraakauthenticatie is niet beschikbaar~Microfoontoestemming is vereist voor spraakauthenticatie~Er is een stemmonster vereist. Geef een opgenomen stemmonster of een vooraf berekende stem-embedding op.~Er is geen stembiometrie geregistreerd. Neem stemmonsters op en registreer ze voordat je je aanmeldt.~Stemsjabloon geregistreerd: %1$s~Stembiometrie geaccepteerd~Stembiometrie kwam niet overeen~Spraakauthenticatie is tijdelijk vergrendeld~Spraakauthenticatie is permanent vergrendeld~Stemmonster is geldig~Het stemmonster ontbreekt of is onvolledig. Geef PCM-audio of een geldige stem-embedding op.~De samplefrequentie van het stemmonster is te laag. Gebruik indien mogelijk 16 kHz mono PCM.~Het stemmonster is te kort. Spreek natuurlijk gedurende minstens één seconde.~Het stemmonster is te lang. Houd het stemmonster onder acht seconden.~Het stemmonster is te zacht. Ga dichter bij de microfoon staan en probeer het opnieuw.~Het stemmonster bevat te weinig variatie. Spreek een duidelijke zin uit en probeer het opnieuw.~Het stemmonster is overstuurd. Verlaag de microfoonversterking of ga iets verder weg staan.~Het stemmonster lijkt herhaald of synthetisch. Neem een nieuwe natuurlijke zin op.~De stem-embedding is ongeldig. Geef een niet-lege spreker-embedding met eindige waarden op.~Spraakopname~Stemmonster opnemen~Bevestig je stem~Neem %1$d natuurlijke stemmonsters van je stem op. Spreek elke keer 2-4 seconden.~Neem één natuurlijk stemmonster op. Spreek 2-4 seconden.~Zin: %1$s~Opname starten~Opname stoppen~Monster gereed~Opgenomen monsters: %1$d/%2$d~Stemmonster gereed~Nog geen stemmonster opgenomen~Registreren~Verifiëren~De stemrecorder is niet beschikbaar op dit apparaat.~Geen spraak gedetecteerd. Spreek duidelijk en probeer het opnieuw.~Het stemmonster is te kort. Spreek natuurlijk gedurende minstens één seconde.~Neem een stemmonster op voordat je doorgaat.~Stemopname mislukt. Probeer het opnieuw.~Luisteren naar stem~Stem gedetecteerd~Stemmonster %1$d van %2$d: opname gestart~Stemmonster %1$d van %2$d opgeslagen~Stemmonster opnemen...~Stem controleren
values-pt-rBR~Tempo esgotado na autenticação por voz~A autenticação por voz não está disponível~A permissão do microfone é obrigatória para a autenticação por voz~É necessária uma amostra de voz. Forneça uma amostra gravada ou um embedding de voz pré-calculado.~Nenhuma biometria de voz está cadastrada. Grave e cadastre amostras de voz antes de se autenticar.~Modelo de voz cadastrado: %1$s~Biometria de voz aceita~A biometria de voz não correspondeu~A autenticação por voz está temporariamente bloqueada~A autenticação por voz está permanentemente bloqueada~A amostra de voz é válida~A amostra de voz está ausente ou incompleta. Forneça áudio PCM ou um embedding de voz válido.~A taxa de amostragem da amostra de voz está muito baixa. Use PCM mono de 16 kHz quando possível.~A amostra de voz está muito curta. Fale naturalmente por pelo menos um segundo.~A amostra de voz está muito longa. Mantenha a amostra de voz abaixo de oito segundos.~A amostra de voz está muito baixa. Aproxime-se do microfone e tente novamente.~A amostra de voz tem pouca variação. Diga uma frase clara e tente novamente.~A amostra de voz está estourada. Reduza o ganho do microfone ou afaste-se um pouco.~A amostra de voz parece repetida ou sintética. Grave uma nova frase natural.~O embedding de voz é inválido. Forneça um embedding de locutor não vazio com valores finitos.~Captura de voz~Gravar amostra de voz~Confirme sua voz~Grave %1$d amostras naturais da sua voz. Fale por 2-4 segundos a cada vez.~Grave uma amostra de voz natural. Fale por 2-4 segundos.~Frase: %1$s~Iniciar gravação~Parar gravação~Amostra pronta~Amostras gravadas: %1$d/%2$d~Amostra de voz pronta~Nenhuma amostra de voz gravada ainda~Cadastrar~Verificar~O gravador de voz não está disponível neste dispositivo.~Nenhuma fala detectada. Fale claramente e tente novamente.~A amostra de voz está muito curta. Fale naturalmente por pelo menos um segundo.~Grave uma amostra de voz antes de continuar.~Falha na gravação de voz. Tente novamente.~Ouvindo a voz~Voz detectada~Amostra de voz %1$d de %2$d: gravação iniciada~Amostra de voz %1$d de %2$d salva~Gravando amostra de voz...~Verificando a voz
values-tr~Sesle kimlik doğrulama zaman aşımına uğradı~Sesle kimlik doğrulama kullanılamıyor~Sesle kimlik doğrulama için mikrofon izni gerekiyor~Bir ses örneği gerekiyor. Kaydedilmiş bir ses örneği veya önceden hesaplanmış bir ses gömme vektörü sağlayın.~Kayıtlı bir ses biyometrisi yok. Kimlik doğrulamadan önce ses örneklerinizi kaydedin.~Ses şablonu kaydedildi: %1$s~Ses biyometrisi kabul edildi~Ses biyometrisi eşleşmedi~Sesle kimlik doğrulama geçici olarak kilitli~Sesle kimlik doğrulama kalıcı olarak kilitli~Ses örneği geçerli~Ses örneği eksik veya tamamlanmamış. PCM ses veya geçerli bir ses gömme vektörü sağlayın.~Ses örneğinin örnekleme hızı çok düşük. Mümkünse 16 kHz mono PCM kullanın.~Ses örneği çok kısa. En az bir saniye doğal şekilde konuşun.~Ses örneği çok uzun. Ses örneğini sekiz saniyenin altında tutun.~Ses örneği çok sessiz. Mikrofona yaklaşın ve tekrar deneyin.~Ses örneğinde çok az çeşitlilik var. Net bir ifade söyleyin ve tekrar deneyin.~Ses örneği kırpılmış. Mikrofon kazancını azaltın veya biraz uzaklaşın.~Ses örneği tekrar edilmiş ya da sentetik görünüyor. Yeni, doğal bir ifade kaydedin.~Ses gömme vektörü geçersiz. Sonlu değerlere sahip boş olmayan bir konuşmacı vektörü sağlayın.~Ses yakalama~Ses örneği kaydet~Sesinizi doğrulayın~Sesinizin %1$d doğal örneğini kaydedin. Her seferinde 2-4 saniye konuşun.~Bir doğal ses örneği kaydedin. 2-4 saniye konuşun.~İfade: %1$s~Kaydı başlat~Kaydı durdur~Örnek hazır~Kaydedilen örnekler: %1$d/%2$d~Ses örneği hazır~Henüz ses örneği kaydedilmedi~Kaydet~Doğrula~Ses kaydedici bu cihazda kullanılamıyor.~Konuşma algılanmadı. Net konuşun ve tekrar deneyin.~Ses örneği çok kısa. En az bir saniye doğal şekilde konuşun.~Devam etmeden önce bir ses örneği kaydedin.~Ses kaydı başarısız oldu. Tekrar deneyin.~Ses dinleniyor~Ses algılandı~Ses örneği %1$d / %2$d: kayıt başladı~Ses örneği %1$d / %2$d kaydedildi~Ses örneği kaydediliyor...~Ses kontrol ediliyor
values-vi~Đã hết thời gian xác thực bằng giọng nói~Xác thực bằng giọng nói không khả dụng~Cần quyền micro để xác thực bằng giọng nói~Cần có mẫu giọng nói. Hãy cung cấp mẫu giọng nói đã ghi hoặc embedding giọng nói đã tính sẵn.~Chưa có sinh trắc học giọng nói nào được đăng ký. Hãy ghi và đăng ký mẫu giọng nói trước khi xác thực.~Đã đăng ký mẫu giọng nói: %1$s~Đã chấp nhận sinh trắc học giọng nói~Sinh trắc học giọng nói không khớp~Xác thực bằng giọng nói tạm thời bị khóa~Xác thực bằng giọng nói bị khóa vĩnh viễn~Mẫu giọng nói hợp lệ~Mẫu giọng nói thiếu hoặc chưa đầy đủ. Hãy cung cấp âm thanh PCM hoặc embedding giọng nói hợp lệ.~Tần số lấy mẫu của mẫu giọng nói quá thấp. Hãy dùng PCM mono 16 kHz nếu có thể.~Mẫu giọng nói quá ngắn. Hãy nói tự nhiên trong ít nhất một giây.~Mẫu giọng nói quá dài. Hãy giữ mẫu giọng nói dưới tám giây.~Mẫu giọng nói quá nhỏ. Hãy lại gần micro hơn và thử lại.~Mẫu giọng nói có quá ít biến thiên. Hãy nói một câu rõ ràng và thử lại.~Mẫu giọng nói bị méo do quá lớn. Hãy giảm gain micro hoặc lùi ra xa hơn một chút.~Mẫu giọng nói có vẻ lặp lại hoặc tổng hợp. Hãy ghi một câu tự nhiên mới.~Embedding giọng nói không hợp lệ. Hãy cung cấp embedding người nói không rỗng với các giá trị hữu hạn.~Thu giọng nói~Ghi mẫu giọng nói~Xác nhận giọng nói của bạn~Hãy ghi %1$d mẫu giọng nói tự nhiên của bạn. Mỗi lần nói trong 2-4 giây.~Hãy ghi một mẫu giọng nói tự nhiên. Nói trong 2-4 giây.~Câu nói: %1$s~Bắt đầu ghi~Dừng ghi~Mẫu đã sẵn sàng~Mẫu đã ghi: %1$d/%2$d~Mẫu giọng nói đã sẵn sàng~Chưa có mẫu giọng nói nào được ghi~Đăng ký~Xác minh~Trình ghi giọng nói không khả dụng trên thiết bị này.~Không phát hiện giọng nói. Hãy nói rõ ràng và thử lại.~Mẫu giọng nói quá ngắn. Hãy nói tự nhiên trong ít nhất một giây.~Hãy ghi mẫu giọng nói trước khi tiếp tục.~Ghi giọng nói thất bại. Hãy thử lại.~Đang nghe giọng nói~Đã phát hiện giọng nói~Mẫu giọng nói %1$d trên %2$d: đã bắt đầu ghi~Mẫu giọng nói %1$d trên %2$d đã được lưu~Đang ghi mẫu giọng nói...~Đang kiểm tra giọng nói
values-id~Waktu autentikasi suara habis~Autentikasi suara tidak tersedia~Izin mikrofon diperlukan untuk autentikasi suara~Sampel suara diperlukan. Berikan sampel suara yang direkam atau embedding suara yang sudah dihitung sebelumnya.~Belum ada biometrik suara yang terdaftar. Rekam dan daftarkan sampel suara sebelum autentikasi.~Template suara terdaftar: %1$s~Biometrik suara diterima~Biometrik suara tidak cocok~Autentikasi suara dikunci sementara~Autentikasi suara dikunci permanen~Sampel suara valid~Sampel suara tidak ada atau tidak lengkap. Berikan audio PCM atau embedding suara yang valid.~Laju sampel suara terlalu rendah. Gunakan PCM mono 16 kHz jika memungkinkan.~Sampel suara terlalu pendek. Bicaralah secara alami setidaknya selama satu detik.~Sampel suara terlalu panjang. Jaga agar sampel suara tetap di bawah delapan detik.~Sampel suara terlalu pelan. Dekatkan diri ke mikrofon lalu coba lagi.~Variasi pada sampel suara terlalu sedikit. Ucapkan frasa yang jelas lalu coba lagi.~Sampel suara terpotong. Kurangi penguatan mikrofon atau menjauhlah sedikit.~Sampel suara tampak berulang atau sintetis. Rekam frasa alami yang baru.~Embedding suara tidak valid. Berikan embedding pembicara yang tidak kosong dengan nilai terhingga.~Pengambilan suara~Rekam sampel suara~Konfirmasikan suara Anda~Rekam %1$d sampel alami suara Anda. Bicaralah selama 2-4 detik setiap kali.~Rekam satu sampel suara alami. Bicaralah selama 2-4 detik.~Frasa: %1$s~Mulai rekam~Hentikan rekam~Sampel siap~Sampel yang direkam: %1$d/%2$d~Sampel suara siap~Belum ada sampel suara yang direkam~Daftarkan~Verifikasi~Perekam suara tidak tersedia di perangkat ini.~Tidak ada ucapan yang terdeteksi. Bicaralah dengan jelas lalu coba lagi.~Sampel suara terlalu pendek. Bicaralah secara alami setidaknya selama satu detik.~Rekam sampel suara sebelum melanjutkan.~Perekaman suara gagal. Coba lagi.~Mendengarkan suara~Suara terdeteksi~Sampel suara %1$d dari %2$d: perekaman dimulai~Sampel suara %1$d dari %2$d disimpan~Merekam sampel suara...~Memeriksa suara
values-ja~音声認証がタイムアウトしました~音声認証は利用できません~音声認証にはマイクの権限が必要です~音声サンプルが必要です。録音済みの音声サンプル、または事前計算済みの音声埋め込みを指定してください。~登録された音声生体認証がありません。認証の前に音声サンプルを録音して登録してください。~音声テンプレートを登録しました: %1$s~音声生体認証が受け入れられました~音声生体認証が一致しませんでした~音声認証は一時的にロックされています~音声認証は恒久的にロックされています~音声サンプルは有効です~音声サンプルが不足しているか不完全です。PCM音声または有効な音声埋め込みを指定してください。~音声サンプルのサンプルレートが低すぎます。可能であれば16 kHzのモノラルPCMを使用してください。~音声サンプルが短すぎます。少なくとも1秒は自然に話してください。~音声サンプルが長すぎます。音声サンプルは8秒未満にしてください。~音声サンプルが小さすぎます。マイクに近づいてもう一度お試しください。~音声サンプルの変化が少なすぎます。はっきりしたフレーズを話してもう一度お試しください。~音声サンプルがクリップしています。マイクのゲインを下げるか、少し離れてください。~音声サンプルが繰り返しまたは合成のように見えます。新しい自然なフレーズを録音してください。~音声埋め込みが無効です。有限値を持つ空でない話者埋め込みを指定してください。~音声キャプチャ~音声サンプルを録音~声を確認してください~自然な音声サンプルを %1$d 件録音してください。毎回2-4秒話してください。~自然な音声サンプルを1件録音してください。2-4秒話してください。~フレーズ: %1$s~録音を開始~録音を停止~サンプルの準備ができました~録音済みサンプル: %1$d/%2$d~音声サンプルの準備ができました~まだ音声サンプルが録音されていません~登録~確認~この端末では音声レコーダーを利用できません。~音声が検出されませんでした。はっきり話してもう一度お試しください。~音声サンプルが短すぎます。少なくとも1秒は自然に話してください。~続行する前に音声サンプルを録音してください。~音声の録音に失敗しました。もう一度お試しください。~音声を聞いています~音声を検出しました~音声サンプル %1$d / %2$d: 録音を開始しました~音声サンプル %1$d / %2$d を保存しました~音声サンプルを録音しています...~音声を確認しています
values-ko~음성 인증 시간이 초과되었습니다~음성 인증을 사용할 수 없습니다~음성 인증에는 마이크 권한이 필요합니다~음성 샘플이 필요합니다. 녹음된 음성 샘플 또는 미리 계산된 음성 임베딩을 제공하세요.~등록된 음성 생체 정보가 없습니다. 인증 전에 음성 샘플을 녹음하고 등록하세요.~음성 템플릿이 등록되었습니다: %1$s~음성 생체 정보가 승인되었습니다~음성 생체 정보가 일치하지 않았습니다~음성 인증이 일시적으로 잠겼습니다~음성 인증이 영구적으로 잠겼습니다~음성 샘플이 유효합니다~음성 샘플이 없거나 불완전합니다. PCM 오디오 또는 유효한 음성 임베딩을 제공하세요.~음성 샘플의 샘플링 속도가 너무 낮습니다. 가능하면 16kHz 모노 PCM을 사용하세요.~음성 샘플이 너무 짧습니다. 최소 1초 이상 자연스럽게 말하세요.~음성 샘플이 너무 깁니다. 음성 샘플을 8초 미만으로 유지하세요.~음성 샘플이 너무 작습니다. 마이크에 더 가까이 가서 다시 시도하세요.~음성 샘플의 변화가 너무 적습니다. 분명한 문구를 말하고 다시 시도하세요.~음성 샘플이 클리핑되었습니다. 마이크 게인을 낮추거나 조금 더 멀리 떨어지세요.~음성 샘플이 반복되었거나 합성된 것처럼 보입니다. 새로운 자연스러운 문구를 녹음하세요.~음성 임베딩이 올바르지 않습니다. 유한한 값을 가진 비어 있지 않은 화자 임베딩을 제공하세요.~음성 캡처~음성 샘플 녹음~음성을 확인하세요~자연스러운 음성 샘플 %1$d개를 녹음하세요. 매번 2-4초 동안 말하세요.~자연스러운 음성 샘플 1개를 녹음하세요. 2-4초 동안 말하세요.~문구: %1$s~녹음 시작~녹음 중지~샘플 준비 완료~녹음된 샘플: %1$d/%2$d~음성 샘플 준비 완료~아직 녹음된 음성 샘플이 없습니다~등록~확인~이 기기에서는 음성 녹음기를 사용할 수 없습니다.~음성이 감지되지 않았습니다. 또렷하게 말하고 다시 시도하세요.~음성 샘플이 너무 짧습니다. 최소 1초 이상 자연스럽게 말하세요.~계속하기 전에 음성 샘플을 녹음하세요.~음성 녹음에 실패했습니다. 다시 시도하세요.~음성을 듣는 중~음성이 감지되었습니다~음성 샘플 %1$d/%2$d: 녹음을 시작했습니다~음성 샘플 %1$d/%2$d 저장됨~음성 샘플 녹음 중...~음성을 확인하는 중
values-zh-rCN~语音认证超时~语音认证不可用~语音认证需要麦克风权限~需要语音样本。请提供已录制的语音样本或预先计算的语音嵌入。~尚未注册任何语音生物识别。请先录制并注册语音样本，然后再进行认证。~语音模板已注册：%1$s~语音生物识别已接受~语音生物识别不匹配~语音认证已被临时锁定~语音认证已被永久锁定~语音样本有效~语音样本缺失或不完整。请提供PCM音频或有效的语音嵌入。~语音样本的采样率过低。请尽可能使用16 kHz单声道PCM。~语音样本过短。请至少自然说话一秒钟。~语音样本过长。请将语音样本控制在八秒以内。~语音样本声音过小。请靠近麦克风后重试。~语音样本变化过少。请说出清晰短语后重试。~语音样本发生削波。请降低麦克风增益或稍微远离一些。~语音样本看起来像重复或合成内容。请录制一段新的自然短语。~语音嵌入无效。请提供包含有限值的非空说话人嵌入。~语音采集~录制语音样本~确认你的声音~请录制 %1$d 个自然语音样本。每次说话持续 2-4 秒。~请录制 1 个自然语音样本。说话持续 2-4 秒。~短语：%1$s~开始录制~停止录制~样本已准备好~已录制样本：%1$d/%2$d~语音样本已准备好~尚未录制语音样本~注册~验证~此设备上的语音录制器不可用。~未检测到语音。请清晰说话后重试。~语音样本过短。请至少自然说话一秒钟。~继续之前请先录制语音样本。~语音录制失败。请重试。~正在监听语音~已检测到语音~语音样本 %1$d/%2$d：已开始录制~语音样本 %1$d/%2$d 已保存~正在录制语音样本...~正在检查语音
values-zh-rTW~語音驗證逾時~語音驗證無法使用~語音驗證需要麥克風權限~需要語音樣本。請提供已錄製的語音樣本或預先計算的語音嵌入。~尚未註冊任何語音生物辨識。請先錄製並註冊語音樣本，再進行驗證。~語音範本已註冊：%1$s~語音生物辨識已接受~語音生物辨識不相符~語音驗證已暫時鎖定~語音驗證已永久鎖定~語音樣本有效~語音樣本缺失或不完整。請提供PCM音訊或有效的語音嵌入。~語音樣本的取樣率過低。請盡可能使用16 kHz單聲道PCM。~語音樣本太短。請至少自然說話一秒鐘。~語音樣本太長。請將語音樣本控制在八秒內。~語音樣本太小聲。請靠近麥克風後再試一次。~語音樣本變化太少。請說出清楚的短語後再試一次。~語音樣本發生削波。請降低麥克風增益或稍微離遠一些。~語音樣本看起來像重複或合成內容。請錄製新的自然短語。~語音嵌入無效。請提供包含有限值的非空說話者嵌入。~語音擷取~錄製語音樣本~確認你的聲音~請錄製 %1$d 個自然語音樣本。每次說話持續 2-4 秒。~請錄製 1 個自然語音樣本。說話持續 2-4 秒。~短語：%1$s~開始錄製~停止錄製~樣本已就緒~已錄製樣本：%1$d/%2$d~語音樣本已就緒~尚未錄製語音樣本~註冊~驗證~此裝置上的語音錄音器無法使用。~未偵測到語音。請清楚說話後再試一次。~語音樣本太短。請至少自然說話一秒鐘。~繼續之前請先錄製語音樣本。~語音錄製失敗。請再試一次。~正在聆聽語音~已偵測到語音~語音樣本 %1$d/%2$d：已開始錄製~語音樣本 %1$d/%2$d 已儲存~正在錄製語音樣本...~正在檢查語音
values-hi~वॉइस प्रमाणीकरण का समय समाप्त हो गया~वॉइस प्रमाणीकरण उपलब्ध नहीं है~वॉइस प्रमाणीकरण के लिए माइक्रोफ़ोन अनुमति आवश्यक है~वॉइस सैंपल आवश्यक है। रिकॉर्ड किया गया वॉइस सैंपल या पहले से गणना किया गया वॉइस एम्बेडिंग प्रदान करें।~कोई वॉइस बायोमेट्रिक पंजीकृत नहीं है। प्रमाणीकरण से पहले वॉइस सैंपल रिकॉर्ड और पंजीकृत करें।~वॉइस टेम्पलेट पंजीकृत: %1$s~वॉइस बायोमेट्रिक स्वीकार किया गया~वॉइस बायोमेट्रिक मेल नहीं खाया~वॉइस प्रमाणीकरण अस्थायी रूप से लॉक है~वॉइस प्रमाणीकरण स्थायी रूप से लॉक है~वॉइस सैंपल मान्य है~वॉइस सैंपल गायब है या अधूरा है। PCM ऑडियो या मान्य वॉइस एम्बेडिंग प्रदान करें।~वॉइस सैंपल की सैंपल दर बहुत कम है। संभव हो तो 16 kHz मोनो PCM का उपयोग करें।~वॉइस सैंपल बहुत छोटा है। कम से कम एक सेकंड तक स्वाभाविक रूप से बोलें।~वॉइस सैंपल बहुत लंबा है। वॉइस सैंपल को आठ सेकंड से कम रखें।~वॉइस सैंपल बहुत धीमा है। माइक्रोफ़ोन के पास जाएँ और फिर से प्रयास करें।~वॉइस सैंपल में बहुत कम विविधता है। कोई स्पष्ट वाक्यांश बोलें और फिर से प्रयास करें।~वॉइस सैंपल क्लिप हो गया है। माइक्रोफ़ोन गेन कम करें या थोड़ा दूर हो जाएँ।~वॉइस सैंपल दोहराया हुआ या कृत्रिम लगता है। एक नया स्वाभाविक वाक्यांश रिकॉर्ड करें।~वॉइस एम्बेडिंग अमान्य है। सीमित मानों वाला खाली न होने वाला स्पीकर एम्बेडिंग प्रदान करें।~वॉइस कैप्चर~वॉइस सैंपल रिकॉर्ड करें~अपनी आवाज़ की पुष्टि करें~अपनी आवाज़ के %1$d स्वाभाविक सैंपल रिकॉर्ड करें। हर बार 2-4 सेकंड तक बोलें।~एक स्वाभाविक वॉइस सैंपल रिकॉर्ड करें। 2-4 सेकंड तक बोलें।~वाक्यांश: %1$s~रिकॉर्डिंग शुरू करें~रिकॉर्डिंग रोकें~सैंपल तैयार है~रिकॉर्ड किए गए सैंपल: %1$d/%2$d~वॉइस सैंपल तैयार है~अभी तक कोई वॉइस सैंपल रिकॉर्ड नहीं किया गया है~पंजीकृत करें~सत्यापित करें~इस डिवाइस पर वॉइस रिकॉर्डर उपलब्ध नहीं है।~कोई आवाज़ नहीं मिली। साफ़ बोलें और फिर से प्रयास करें।~वॉइस सैंपल बहुत छोटा है। कम से कम एक सेकंड तक स्वाभाविक रूप से बोलें।~आगे बढ़ने से पहले वॉइस सैंपल रिकॉर्ड करें।~वॉइस रिकॉर्डिंग विफल हुई। फिर से प्रयास करें।~आवाज़ सुनी जा रही है~आवाज़ मिली~वॉइस सैंपल %1$d / %2$d: रिकॉर्डिंग शुरू हुई~वॉइस सैंपल %1$d / %2$d सहेजा गया~वॉइस सैंपल रिकॉर्ड किया जा रहा है...~आवाज़ की जाँच की जा रही है
values-ar~انتهت مهلة المصادقة الصوتية~المصادقة الصوتية غير متاحة~يتطلب استخدام المصادقة الصوتية إذن الميكروفون~مطلوب عينة صوتية. قدّم عينة صوتية مسجلة أو تضمينًا صوتيًا محسوبًا مسبقًا.~لا توجد أي قياسات حيوية صوتية مسجلة. سجّل عينات صوتية قبل المصادقة.~تم تسجيل قالب صوتي: %1$s~تم قبول القياسات الحيوية الصوتية~لم تتطابق القياسات الحيوية الصوتية~المصادقة الصوتية مقفلة مؤقتًا~المصادقة الصوتية مقفلة بشكل دائم~العينة الصوتية صالحة~العينة الصوتية مفقودة أو غير مكتملة. قدّم صوت PCM أو تضمينًا صوتيًا صالحًا.~معدل أخذ العينات للعينة الصوتية منخفض جدًا. استخدم PCM أحاديًا بتردد 16 كيلوهرتز متى أمكن.~العينة الصوتية قصيرة جدًا. تحدث بشكل طبيعي لمدة ثانية واحدة على الأقل.~العينة الصوتية طويلة جدًا. أبقِ العينة الصوتية أقل من ثماني ثوانٍ.~العينة الصوتية منخفضة جدًا. اقترب من الميكрофون وحاول مرة أخرى.~العينة الصوتية تفتقر إلى التنوع. انطق عبارة واضحة وحاول مرة أخرى.~العينة الصوتية مشوشة. خفّض كسب الميكروفون أو ابتعد قليلًا.~تبدو العينة الصوتية مكررة أو مصطنعة. سجّل عبارة طبيعية جديدة.~تضمين الصوت غير صالح. قدّم تضمين متحدث غير فارغ بقيم منتهية.~التقاط الصوت~تسجيل عينة صوتية~أكّد صوتك~سجّل %1$d عينات طبيعية من صوتك. تحدث لمدة 2-4 ثوانٍ في كل مرة.~سجّل عينة صوتية طبيعية واحدة. تحدث لمدة 2-4 ثوانٍ.~العبارة: %1$s~بدء التسجيل~إيقاف التسجيل~العينة جاهزة~العينات المسجلة: %1$d/%2$d~العينة الصوتية جاهزة~لم يتم تسجيل أي عينة صوتية بعد~تسجيل~تحقق~مسجل الصوت غير متاح على هذا الجهاز.~لم يتم اكتشاف أي كلام. تحدث بوضوح وحاول مرة أخرى.~العينة الصوتية قصيرة جدًا. تحدث بشكل طبيعي لمدة ثانية واحدة على الأقل.~سجّل عينة صوتية قبل المتابعة.~فشل تسجيل الصوت. حاول مرة أخرى.~جارٍ الاستماع إلى الصوت~تم اكتشاف الصوت~العينة الصوتية %1$d من %2$d: بدأ التسجيل~تم حفظ العينة الصوتية %1$d من %2$d~جارٍ تسجيل العينة الصوتية...~جارٍ التحقق من الصوت
'@
$voiceRows = $voiceRows -split '\r?\n'

$sharedRows = @'
values-en~Software biometric module %1$s cannot satisfy a hardware-backed CryptoObject~Unblock device microphone~Unblock~Verify it’s you~Use your biometric to continue
values-uk~Програмний біометричний модуль %1$s не може використовувати апаратно-захищений CryptoObject~Розблокувати мікрофон пристрою~Розблокувати~Підтвердьте, що це ви~Використайте біометрію, щоб продовжити
values-ru~Программный биометрический модуль %1$s не может использовать аппаратно-защищенный CryptoObject~Разблокировать микрофон устройства~Разблокировать~Подтвердите, что это вы~Используйте биометрию, чтобы продолжить
values-de~Das Software-Biometriemodul %1$s kann kein hardwaregestütztes CryptoObject verwenden~Mikrofon des Geräts entsperren~Entsperren~Bestätige, dass du es bist~Verwende deine Biometrie, um fortzufahren
values-es~El módulo biométrico por software %1$s no puede usar un CryptoObject respaldado por hardware~Desbloquear el micrófono del dispositivo~Desbloquear~Verifica que eres tú~Usa tu biometría para continuar
values-b+es+419~El módulo biométrico por software %1$s no puede usar un CryptoObject respaldado por hardware~Desbloquear el micrófono del dispositivo~Desbloquear~Verifica que eres tú~Usa tu biometría para continuar
values-fr~Le module biométrique logiciel %1$s ne peut pas utiliser un CryptoObject protégé par le matériel~Débloquer le microphone de l'appareil~Débloquer~Vérifiez qu'il s'agit bien de vous~Utilisez votre biométrie pour continuer
values-it~Il modulo biometrico software %1$s non può usare un CryptoObject supportato dall'hardware~Sblocca il microfono del dispositivo~Sblocca~Verifica che sia davvero tu~Usa la biometria per continuare
values-nl~De software-biometriemodule %1$s kan geen hardware-ondersteund CryptoObject gebruiken~Microfoon van apparaat deblokkeren~Deblokkeren~Controleer of jij het bent~Gebruik je biometrie om door te gaan
values-pt-rBR~O módulo biométrico por software %1$s não pode usar um CryptoObject com suporte de hardware~Desbloquear o microfone do dispositivo~Desbloquear~Confirme que é você~Use sua biometria para continuar
values-tr~Yazılım biyometri modülü %1$s donanım destekli bir CryptoObject kullanamaz~Cihaz mikrofonunun engelini kaldır~Engeli kaldır~Bunun siz olduğunuzu doğrulayın~Devam etmek için biyometrinizi kullanın
values-vi~Mô-đun sinh trắc học phần mềm %1$s không thể dùng CryptoObject được phần cứng bảo vệ~Bỏ chặn micrô của thiết bị~Bỏ chặn~Xác minh đó là bạn~Dùng sinh trắc học để tiếp tục
values-id~Modul biometrik perangkat lunak %1$s tidak dapat menggunakan CryptoObject yang didukung perangkat keras~Buka blokir mikrofon perangkat~Buka blokir~Verifikasi bahwa ini Anda~Gunakan biometrik Anda untuk melanjutkan
values-ja~ソフトウェア生体認証モジュール %1$s はハードウェア保護されたCryptoObjectを使用できません~デバイスのマイクのブロックを解除~解除~本人確認をしてください~続行するには生体認証を使用してください
values-ko~소프트웨어 생체 인식 모듈 %1$s은(는) 하드웨어 기반 CryptoObject를 사용할 수 없습니다~기기 마이크 차단 해제~차단 해제~본인 여부를 확인하세요~계속하려면 생체 인식을 사용하세요
values-zh-rCN~软件生物识别模块 %1$s 无法使用硬件支持的CryptoObject~解除设备麦克风限制~解除限制~验证是否为你本人~使用生物识别以继续
values-zh-rTW~軟體生物辨識模組 %1$s 無法使用硬體支援的CryptoObject~解除裝置麥克風限制~解除限制~確認是你本人~使用生物辨識以繼續
values-hi~सॉफ़्टवेयर बायोमेट्रिक मॉड्यूल %1$s हार्डवेयर-समर्थित CryptoObject का उपयोग नहीं कर सकता~डिवाइस माइक्रोफ़ोन अनब्लॉक करें~अनब्लॉक करें~पुष्टि करें कि यह आप हैं~जारी रखने के लिए अपनी बायोमेट्रिक का उपयोग करें
values-ar~تعذر على وحدة القياسات الحيوية البرمجية %1$s استخدام CryptoObject محميًا بالعتاد~إلغاء حظر ميكروفون الجهاز~إلغاء الحظر~أكّد أنك أنت~استخدم بصمتك الحيوية للمتابعة
'@
$sharedRows = $sharedRows -split '\r?\n'

function Save-Xml([xml]$doc, [string]$path) {
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Indent = $true
    $settings.IndentChars = '    '
    $settings.NewLineChars = "`r`n"
    $settings.NewLineHandling = [System.Xml.NewLineHandling]::Replace
    $settings.Encoding = New-Object System.Text.UTF8Encoding($false)
    $writer = [System.Xml.XmlWriter]::Create($path, $settings)
    $doc.Save($writer)
    $writer.Dispose()
}

function Escape-AndroidString([string]$value) {
    $value = $value -replace "\\\\'", "’"
    return $value.Replace("'", "’")
}

function Set-StringValues([string]$path, [string[]]$keys, [string[]]$values, [string]$anchorName) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing locale file: $path"
    }
    [xml]$doc = Get-Content -LiteralPath $path -Raw
    for ($i = 0; $i -lt $keys.Count; $i++) {
        $key = $keys[$i]
        $value = $values[$i]
        $node = @($doc.resources.string | Where-Object { $_.name -eq $key })[0]
        if ($null -eq $node) {
            $node = $doc.CreateElement('string')
            $node.SetAttribute('name', $key)
            $node.InnerText = Escape-AndroidString $value
            $anchor = @($doc.resources.string | Where-Object { $_.name -eq $anchorName })[0]
            if ($null -ne $anchor) {
                $null = $doc.resources.InsertAfter($node, $anchor)
                $anchorName = $key
            }
            else {
                $null = $doc.resources.AppendChild($node)
            }
        }
        else {
            $node.InnerText = Escape-AndroidString $value
        }
    }
    Save-Xml $doc $path
}

foreach ($row in $voiceRows) {
    if ([string]::IsNullOrWhiteSpace($row)) { continue }
    $parts = $row.Trim() -split '~'
    $locale = $parts[0].Trim()
    $values = $parts[1..($parts.Length - 1)]
    if ($values.Length -ne $voiceKeys.Length) {
        throw \"Voice locale $locale has $($values.Length) values, expected $($voiceKeys.Length)\"
    }
    $path = Join-Path (Get-Location).Path ("biometric-custom-voice\src\main\res\{0}\strings.xml" -f $locale)
    Set-StringValues $path $voiceKeys $values 'biometriccompat_voice_help_timeout'
}

foreach ($row in $sharedRows) {
    if ([string]::IsNullOrWhiteSpace($row)) { continue }
    $parts = $row.Trim() -split '~'
    $locale = $parts[0].Trim()
    $values = $parts[1..($parts.Length - 1)]
    if ($values.Length -ne $sharedKeys.Length) {
        throw \"Shared locale $locale has $($values.Length) values, expected $($sharedKeys.Length)\"
    }
    $path = Join-Path (Get-Location).Path ("biometric\src\main\res\{0}\strings.xml" -f $locale)
    Set-StringValues $path $sharedKeys $values 'biometriccompat_required_crypto_missing_error'
}

Write-Output 'Locale updates applied.'
