package dev.skomlach.biometric.compat.engine;

import androidx.annotation.RestrictTo;

@RestrictTo(RestrictTo.Scope.LIBRARY)
public interface BiometricCodes {
    int BIOMETRIC_ACQUIRED_GOOD = 0;
    int BIOMETRIC_ACQUIRED_IMAGER_DIRTY = 3;
    int BIOMETRIC_ACQUIRED_INSUFFICIENT = 2;
    int BIOMETRIC_ACQUIRED_PARTIAL = 1;
    int BIOMETRIC_ACQUIRED_TOO_FAST = 5;
    int BIOMETRIC_ACQUIRED_TOO_SLOW = 4;
    int BIOMETRIC_ERROR_CANCELED = 5;
    int BIOMETRIC_ERROR_HW_NOT_PRESENT = 12;
    int BIOMETRIC_ERROR_HW_UNAVAILABLE = 1;
    int BIOMETRIC_ERROR_LOCKOUT = 7;
    int BIOMETRIC_ERROR_LOCKOUT_PERMANENT = 9;
    int BIOMETRIC_ERROR_NO_BIOMETRICS = 11;
    int BIOMETRIC_ERROR_NO_SPACE = 4;
    int BIOMETRIC_ERROR_TIMEOUT = 3;
    int BIOMETRIC_ERROR_UNABLE_TO_PROCESS = 2;
    int BIOMETRIC_ERROR_USER_CANCELED = 10;
    int BIOMETRIC_ERROR_VENDOR = 8;
    int BIOMETRIC_ERROR_NEGATIVE_BUTTON = 13;
}
