package android.hardware.biometrics;

import android.os.Build;

import androidx.annotation.RequiresApi;

@RequiresApi(api = Build.VERSION_CODES.TIRAMISU)
public interface IOplusBiometricFaceConstantsEx {
    int FACE_ACQUIRED_CAMERA_PREVIEW = 1001;
    int FACE_ACQUIRED_DEPTH_TOO_NEARLY = 303;
    int FACE_ACQUIRED_DOE_CHECK = 307;
    int FACE_ACQUIRED_DOE_PRECHECK = 306;
    int FACE_ACQUIRED_FACEDOE_IMAGE_READY = 308;
    int FACE_ACQUIRED_IR_HKER = 305;
    int FACE_ACQUIRED_IR_PATTERN = 304;
    int FACE_ACQUIRED_MOUTH_OCCLUSION = 113;
    int FACE_ACQUIRED_MULTI_FACE = 116;
    int FACE_ACQUIRED_NOSE_OCCLUSION = 115;
    int FACE_ACQUIRED_NOT_FRONTAL_FACE = 114;
    int FACE_ACQUIRED_NO_FACE = 101;
    int FACE_ACQUIRED_NO_FOCUS = 112;
    int FACE_ACQUIRED_SWITCH_DEPTH = 302;
    int FACE_ACQUIRED_SWITCH_IR = 301;
    int FACE_AUTHENTICATE_AUTO = 0;
    int FACE_AUTHENTICATE_BY_FINGERPRINT = 3;
    int FACE_AUTHENTICATE_BY_USER = 1;
    int FACE_AUTHENTICATE_BY_USER_WITH_ANIM = 2;
    int FACE_AUTHENTICATE_PAY = 4;
    int FACE_ERROR_CAMERA_UNAVAILABLE = 0;
    String FACE_KEYGUARD_CANCELED_BY_SCREEN_OFF = "cancelRecognitionByScreenOff";
    int FACE_WITH_EYES_CLOSED = 111;
}
